### ISSUE TITLE
smarter search on delete/change/regenerate/rename/transfer

### ISSUE THREAD

**Issue by conradkdotcom** [conradkdotcom/rooster#27] opened 2017-07-24 21:31 UTC
Whenever you call `rooster get <app>`, Rooster will **try to find app names that match your query with a fuzzy search**. This means that `rooster get ggl` will match `Google` but also `Goggles`. When that happens, Rooster allows you to choose whether you want the password for `Google` or `Goggles`. This is mostly helpful when you dont remember the exact name of an app.

You can see this in action by running the following commands:
```bash
# create a temporary rooster file for tests
rm -f /tmp/test.rooster
export ROOSTER_FILE=/tmp/test.rooster

# add a password for Google
printf "y\ntest\nn\n" | rooster generate Google my@email.com

# add a password for Goggles
printf "test\ntest\n" | rooster generate Goggles my@email.com

# now, get the password for "ggl" as described above
printf "test\n2\n" | rooster get --show ggl
```

You'll see that at the last command `rooster get --show ggl`, Rooster will suggest both passwords. Typing in `2`, as in the test script above, selects the password for `Google`.

This is the behavior we should have in all commands that require searching for a password: `delete`, `change`, `regenerate`, `rename`, `transfer`.

Tasks:
- [x] mimic the `rooster get` behavior for password search on the following commands:
  - [x] `delete`
  - [x] `change`
  - [x] `regenerate`
  - [x] `rename`
  - [x] `transfer`
- [x] add yourself to the contributors' list in README.md in alphabetical order
- [x] bump up the minor version (x.X.x) in Cargo.toml so I can publish to crates.io

Thanks a lot for your help ❤️ If you have any questions, just let us know and we'll jump in to help.

**Comment by yamnikov-oleg** [comment] 2017-07-31 20:53
I've got an all-ready pull request resolving this issue :) But before sending it I want to rebase it onto the latest master.

The problem is, I can't build the master, because cargo can't resolve `rpassword` and `rprompt` dependencies (they are referenced by relative paths in Cargo.toml). Would you point me, where can I get these packages? Thanks!

**Comment by conradkdotcom** [comment] 2017-07-31 21:11
Hi @yamnikov-oleg ! Thanks a lot for your help ! 👍 ❤️ 

Sorry about the broken paths. I was changing some stuff in those crates.

You can replace the paths with this in `Cargo.toml`:
```toml
rprompt = "1.0"
rpassword = "0.4"
```

This should allow you to compile. Let me know if that works :-)

**Comment by yamnikov-oleg** [comment] 2017-08-01 10:16
@conradkdotcom With your latest commit it all works, thank you :) I'm just going to tidy up the code and then will send it.

**Closed** 2017-08-03 18:04 UTC
Labels: assigned, feature
